# Generated by Django 5.2.16 on 2026-08-07 12:15

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_assistant', '0011_pgvector_indexing_status'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LlmJob',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('kind', models.CharField(choices=[('chat', 'Chat'), ('chat_stream', 'Chat stream')], max_length=32)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('running', 'Running'), ('done', 'Done'), ('error', 'Error')], db_index=True, default='pending', max_length=16)),
                ('payload', models.JSONField(blank=True, default=dict)),
                ('result', models.JSONField(blank=True, default=dict)),
                ('error', models.TextField(blank=True, default='')),
                ('event_seq', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('session', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='llm_jobs', to='ai_assistant.chatsession')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ai_assistant_llm_jobs', to=settings.AUTH_USER_MODEL)),
                ('user_message', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='llm_jobs', to='ai_assistant.chatmessage')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='LlmJobEvent',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('seq', models.PositiveIntegerField()),
                ('event', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='ai_assistant.llmjob')),
            ],
            options={
                'ordering': ['seq'],
            },
        ),
        migrations.AddIndex(
            model_name='llmjob',
            index=models.Index(fields=['user', '-created_at'], name='ai_assistan_user_id_1c5a3c_idx'),
        ),
        migrations.AddIndex(
            model_name='llmjob',
            index=models.Index(fields=['status', '-created_at'], name='ai_assistan_status_6b2c19_idx'),
        ),
        migrations.AddIndex(
            model_name='llmjobevent',
            index=models.Index(fields=['job', 'seq'], name='ai_assistan_job_id_526d34_idx'),
        ),
        migrations.AddConstraint(
            model_name='llmjobevent',
            constraint=models.UniqueConstraint(fields=('job', 'seq'), name='ai_assistant_llmjobevent_job_seq'),
        ),
    ]
